name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest #ubuntu-20.04
    steps:
      # JDK version 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle build
      - name: Build with Gradle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          run: |
            cd ../../var/www/Backend/
            ./gradlew build

      # Spring 어플리케이션 Docker Image 빌드
      - name: Build Docker Image For Spring
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          run: |
            cd
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/connect_x .
            sudo docker push ${{ secrets.DOCKER_USERNAME }}/connect_x
          
      # 서버에서 Docker 이미지 실행
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/connect_x
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/connect_x:latest
            docker-compose up -d
